/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.

Fajl Schedule.java u package-u Screens.User je osnovni fajl u kojem smo smjestili sve funkcionalnosti koje imamo za korisnika.
U okviru ovog fajla imamo "Source" i "Design". Pod "Source" je smjesten sav kod koji predstavlja odredjene funkcionalnosti.
Pod "Design" imamo dizajner koji mozemo koristiti za olaksano dizajniranje izgleda pojedinih ekrana.
 */
package Screens.User;

import db_queries.GetSchedules;
import db_queries.GetTrainers;
import db_queries.SetReservations;
import entities.Reservations;
import entities.Schedules;
import java.awt.Dimension;
import java.awt.GridLayout;
import java.awt.Toolkit;
import java.util.ArrayList;
import java.util.List;
import javax.swing.GroupLayout;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.TableColumn;

// Klasa "Schedule" je glavna klasa koju koristimo.
/**
 *
 * @author User
 */
public class Schedule extends javax.swing.JFrame {
    //Metoda ispod predstavlja KONSTRUKTOR BEZ PARAMETARA za klasu Schedule.
    // Konstruktori su specijalne funkcije u klasama koje sluze za postavljanje default-nih vrijednosti za atribute klase prilikom inicijaliziranja objekta tipa klase.
    // Primjer: User u = new User(ime, prezime);
    
    // Konstruktor za klasu Schedule inicijalizira sve komponente koje se koriste prilikom dizajna.
    /**
     * Creates new form Test
     */
    public Schedule() {
        initComponents();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        Menu_items = new javax.swing.JPanel();
        homeButton = new javax.swing.JButton();
        fitnessButton = new javax.swing.JButton();
        crossfitButton = new javax.swing.JButton();
        zumbaButton = new javax.swing.JButton();
        yogaButton = new javax.swing.JButton();
        pilatesButton = new javax.swing.JButton();
        bodybuildingButton = new javax.swing.JButton();
        Menu_item_content = new javax.swing.JPanel();
        homePanel = new javax.swing.JPanel();
        backgroundImagePanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        fitnessPanel = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jPanel13 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        fitnessTable = new javax.swing.JTable();
        jLabel11 = new javax.swing.JLabel();
        crossfitPanel = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        jPanel15 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        crossfitTable = new javax.swing.JTable();
        jLabel15 = new javax.swing.JLabel();
        zumbaPanel = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        jPanel9 = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        jPanel16 = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        zumbaTable = new javax.swing.JTable();
        jLabel18 = new javax.swing.JLabel();
        yogaPanel = new javax.swing.JPanel();
        jLabel19 = new javax.swing.JLabel();
        jPanel10 = new javax.swing.JPanel();
        jLabel20 = new javax.swing.JLabel();
        jPanel17 = new javax.swing.JPanel();
        jScrollPane5 = new javax.swing.JScrollPane();
        yogaTable = new javax.swing.JTable();
        jLabel21 = new javax.swing.JLabel();
        pilatesPanel = new javax.swing.JPanel();
        jLabel22 = new javax.swing.JLabel();
        jPanel11 = new javax.swing.JPanel();
        jLabel23 = new javax.swing.JLabel();
        jPanel18 = new javax.swing.JPanel();
        jScrollPane6 = new javax.swing.JScrollPane();
        pilatesTable = new javax.swing.JTable();
        jLabel24 = new javax.swing.JLabel();
        bodybuildingPanel = new javax.swing.JPanel();
        jLabel25 = new javax.swing.JLabel();
        jPanel12 = new javax.swing.JPanel();
        jLabel26 = new javax.swing.JLabel();
        jPanel19 = new javax.swing.JPanel();
        jScrollPane7 = new javax.swing.JScrollPane();
        bodybuildingTable = new javax.swing.JTable();
        jLabel27 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setPreferredSize(new java.awt.Dimension(1024, 768));
        jPanel1.setLayout(new java.awt.BorderLayout());

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setPreferredSize(new java.awt.Dimension(200, 600));
        jPanel2.setLayout(new java.awt.GridBagLayout());

        Menu_items.setBackground(new java.awt.Color(255, 255, 255));
        Menu_items.setPreferredSize(new java.awt.Dimension(180, 550));
        Menu_items.setLayout(new java.awt.GridLayout(7, 1, 2, 20));

        homeButton.setBackground(new java.awt.Color(255, 255, 255));
        homeButton.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        homeButton.setForeground(new java.awt.Color(242, 100, 34));
        homeButton.setText("Home");
        homeButton.setAlignmentY(0.0F);
        homeButton.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(242, 100, 34)));
        homeButton.setContentAreaFilled(false);
        homeButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        homeButton.setFocusPainted(false);
        homeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                homeButtonActionPerformed(evt);
            }
        });
        Menu_items.add(homeButton);

        fitnessButton.setBackground(new java.awt.Color(255, 255, 255));
        fitnessButton.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        fitnessButton.setForeground(new java.awt.Color(242, 100, 34));
        fitnessButton.setText("Fitness");
        fitnessButton.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(242, 100, 34)));
        fitnessButton.setContentAreaFilled(false);
        fitnessButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        fitnessButton.addContainerListener(new java.awt.event.ContainerAdapter() {
            public void componentAdded(java.awt.event.ContainerEvent evt) {
                fitnessButtonComponentAdded(evt);
            }
        });
        fitnessButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fitnessButtonActionPerformed(evt);
            }
        });
        Menu_items.add(fitnessButton);

        crossfitButton.setBackground(new java.awt.Color(255, 255, 255));
        crossfitButton.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        crossfitButton.setForeground(new java.awt.Color(242, 100, 34));
        crossfitButton.setText("Crossfit");
        crossfitButton.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(242, 100, 34)));
        crossfitButton.setContentAreaFilled(false);
        crossfitButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        crossfitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                crossfitButtonActionPerformed(evt);
            }
        });
        Menu_items.add(crossfitButton);

        zumbaButton.setBackground(new java.awt.Color(255, 255, 255));
        zumbaButton.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        zumbaButton.setForeground(new java.awt.Color(242, 100, 34));
        zumbaButton.setText("Zumba");
        zumbaButton.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(242, 100, 34)));
        zumbaButton.setContentAreaFilled(false);
        zumbaButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        zumbaButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                zumbaButtonActionPerformed(evt);
            }
        });
        Menu_items.add(zumbaButton);

        yogaButton.setBackground(new java.awt.Color(255, 255, 255));
        yogaButton.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        yogaButton.setForeground(new java.awt.Color(242, 100, 34));
        yogaButton.setText("Yoga");
        yogaButton.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(242, 100, 34)));
        yogaButton.setContentAreaFilled(false);
        yogaButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        yogaButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                yogaButtonActionPerformed(evt);
            }
        });
        Menu_items.add(yogaButton);

        pilatesButton.setBackground(new java.awt.Color(255, 255, 255));
        pilatesButton.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        pilatesButton.setForeground(new java.awt.Color(242, 100, 34));
        pilatesButton.setText("Pilates");
        pilatesButton.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(242, 100, 34)));
        pilatesButton.setContentAreaFilled(false);
        pilatesButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        pilatesButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pilatesButtonActionPerformed(evt);
            }
        });
        Menu_items.add(pilatesButton);

        bodybuildingButton.setBackground(new java.awt.Color(255, 255, 255));
        bodybuildingButton.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        bodybuildingButton.setForeground(new java.awt.Color(242, 100, 34));
        bodybuildingButton.setText("Bodybuilding");
        bodybuildingButton.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(242, 100, 34)));
        bodybuildingButton.setContentAreaFilled(false);
        bodybuildingButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        bodybuildingButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bodybuildingButtonActionPerformed(evt);
            }
        });
        Menu_items.add(bodybuildingButton);

        jPanel2.add(Menu_items, new java.awt.GridBagConstraints());

        jPanel1.add(jPanel2, java.awt.BorderLayout.LINE_START);

        Menu_item_content.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 1, 0, 0, new java.awt.Color(242, 100, 34)));
        Menu_item_content.setLayout(new java.awt.CardLayout());

        backgroundImagePanel.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(242, 100, 34)));
        backgroundImagePanel.setPreferredSize(new java.awt.Dimension(800, 300));
        backgroundImagePanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/1.jpg"))); // NOI18N
        jLabel1.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(242, 100, 34)));
        jLabel1.setMaximumSize(new java.awt.Dimension(867, 380));
        jLabel1.setMinimumSize(new java.awt.Dimension(867, 380));
        jLabel1.setPreferredSize(new java.awt.Dimension(867, 380));
        backgroundImagePanel.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 840, 300));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 0, 0, 0, new java.awt.Color(242, 100, 34)));
        jPanel3.setPreferredSize(new java.awt.Dimension(830, 382));

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));

        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel6.setText("Our Story");

        jLabel8.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel8.setText("<html> <p style=\"text-align: justify;\">GymFit was founded in 2012 as a family owned and operated business. The GymFit founders didn’t want it to be just another gym equipment retailer - they wanted to be the best in the industry and set their minds to doing so! Since its birth, GymFit has grown into one of Bosnia’s largest fitness gym having helped over 2500 customers live longer, happier and healthier lives.</p> </html>");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 378, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 10, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(279, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanel6.setBackground(new java.awt.Color(255, 255, 255));

        jLabel7.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel7.setText("What we do");
        jLabel7.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);

        jLabel9.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel9.setText("<html> <p style=\"text-align: justify;\">We want to help you live a fit and healthy lifestyle! We do this by helping you find the most suitable equipment for your workout, keeping your budget, lifestyle and fitness goals in mind. We stock a wide range of gym equipment, with strength equipment, cardio, cross training and so much more. Our awesome team is always keen to help, so please call us to discuss your needs.</p> </html>");
        jLabel9.setFocusCycleRoot(true);

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 383, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 370, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(20, 20, 20))))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jLabel2.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel2.setText("<html>\n<p style=\"color:#f26422; font-weight: bold;\" >&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;6</>\n<p>PROGRAMS</p>\n</html>");

        jLabel3.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel3.setText("<html>\n<p style=\"color:#f26422; font-weight: bold;\" >&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;2500+</>\n<p>CUSTOMERS</p>\n</html>");

        jLabel4.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel4.setText("<html>\n<p style=\"color:#f26422; font-weight: bold;\" >&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;5</>\n<p>COACHES</p>\n</html>");

        jLabel5.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel5.setText("<html>\n<p style=\"color:#f26422; font-weight: bold;\" >&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;15000+</>\n<p>TRAINING HOURS</p>\n</html>");

        javax.swing.GroupLayout homePanelLayout = new javax.swing.GroupLayout(homePanel);
        homePanel.setLayout(homePanelLayout);
        homePanelLayout.setHorizontalGroup(
            homePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(backgroundImagePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, 840, Short.MAX_VALUE)
            .addGroup(homePanelLayout.createSequentialGroup()
                .addGap(68, 68, 68)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(81, 81, 81)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(77, 77, 77)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(77, 77, 77))
        );
        homePanelLayout.setVerticalGroup(
            homePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(homePanelLayout.createSequentialGroup()
                .addComponent(backgroundImagePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(homePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        Menu_item_content.add(homePanel, "card2");

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/fitness.jpg"))); // NOI18N
        jLabel10.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(242, 100, 34)));
        jLabel10.setMaximumSize(new java.awt.Dimension(867, 380));
        jLabel10.setMinimumSize(new java.awt.Dimension(867, 380));
        jLabel10.setPreferredSize(new java.awt.Dimension(867, 380));

        jPanel7.setBackground(new java.awt.Color(255, 255, 255));
        jPanel7.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 0, 0, 0, new java.awt.Color(242, 100, 34)));
        jPanel7.setPreferredSize(new java.awt.Dimension(840, 400));

        jLabel12.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel12.setText("<html>\n<p style=\"text-align: justify;\">If you're looking to tone up, build muscle or burn fat, this Fitness class using weights will give you an all over, total body workout. As you lift, curl and lunge your way through the range of upbeat exercises, the time will fly by.</p>\n</html>");

        fitnessTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"08:00", null, null, null, null, null, null, null},
                {"10:00", null, null, null, null, null, null, null},
                {"12:00", null, null, null, null, null, null, null},
                {"14:00", null, null, null, null, null, null, null},
                {"16:00", null, null, null, null, null, null, null},
                {"18:00", null, null, null, null, null, null, null},
                {"20:00", null, null, null, null, null, null, null}
            },
            new String [] {
                "", "Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday", "Sunday"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        fitnessTable.setColumnSelectionAllowed(true);
        fitnessTable.setRowHeight(35);
        fitnessTable.getTableHeader().setReorderingAllowed(false);
        fitnessTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                fitnessTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(fitnessTable);
        fitnessTable.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        if (fitnessTable.getColumnModel().getColumnCount() > 0) {
            fitnessTable.getColumnModel().getColumn(0).setResizable(false);
            fitnessTable.getColumnModel().getColumn(1).setResizable(false);
            fitnessTable.getColumnModel().getColumn(2).setResizable(false);
            fitnessTable.getColumnModel().getColumn(3).setResizable(false);
            fitnessTable.getColumnModel().getColumn(4).setResizable(false);
            fitnessTable.getColumnModel().getColumn(5).setResizable(false);
            fitnessTable.getColumnModel().getColumn(6).setResizable(false);
            fitnessTable.getColumnModel().getColumn(7).setResizable(false);
        }

        javax.swing.GroupLayout jPanel13Layout = new javax.swing.GroupLayout(jPanel13);
        jPanel13.setLayout(jPanel13Layout);
        jPanel13Layout.setHorizontalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel13Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 785, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel13Layout.setVerticalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 309, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jPanel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, 805, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jLabel11.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 37, 12));
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel11.setText("What is Fitness?");

        javax.swing.GroupLayout fitnessPanelLayout = new javax.swing.GroupLayout(fitnessPanel);
        fitnessPanel.setLayout(fitnessPanelLayout);
        fitnessPanelLayout.setHorizontalGroup(
            fitnessPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, fitnessPanelLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(fitnessPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 840, javax.swing.GroupLayout.PREFERRED_SIZE)))
            .addGroup(fitnessPanelLayout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 699, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        fitnessPanelLayout.setVerticalGroup(
            fitnessPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(fitnessPanelLayout.createSequentialGroup()
                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel11)
                .addGap(18, 18, 18)
                .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, 404, Short.MAX_VALUE))
        );

        Menu_item_content.add(fitnessPanel, "card3");

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/crossfit_2.jpg"))); // NOI18N
        jLabel13.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(242, 100, 34)));
        jLabel13.setMaximumSize(new java.awt.Dimension(867, 380));
        jLabel13.setMinimumSize(new java.awt.Dimension(867, 380));
        jLabel13.setPreferredSize(new java.awt.Dimension(867, 380));

        jPanel8.setBackground(new java.awt.Color(255, 255, 255));
        jPanel8.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 0, 0, 0, new java.awt.Color(242, 100, 34)));
        jPanel8.setPreferredSize(new java.awt.Dimension(840, 400));

        jLabel14.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel14.setText("<html> <p style=\"text-align: justify;\">CrossFit is a lifestyle characterized by safe, effective exercise and sound nutrition. CrossFit can be used to accomplish any goal, from improved health to weight loss to better performance. The program works for everyone — people who are just starting out and people who have trained for years.</p> </html>");

        jPanel15.setPreferredSize(new java.awt.Dimension(805, 309));

        crossfitTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"08:00", null, null, null, null, null, null, null},
                {"10:00", null, null, null, null, null, null, null},
                {"12:00", null, null, null, null, null, null, null},
                {"14:00", null, null, null, null, null, null, null},
                {"16:00", null, null, null, null, null, null, null},
                {"18:00", null, null, null, null, null, null, null},
                {"20:00", null, null, null, null, null, null, null}
            },
            new String [] {
                "", "Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday", "Sunday"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        crossfitTable.setRowHeight(35);
        crossfitTable.getTableHeader().setReorderingAllowed(false);
        crossfitTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                crossfitTableMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(crossfitTable);
        crossfitTable.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        if (crossfitTable.getColumnModel().getColumnCount() > 0) {
            crossfitTable.getColumnModel().getColumn(0).setResizable(false);
            crossfitTable.getColumnModel().getColumn(1).setResizable(false);
            crossfitTable.getColumnModel().getColumn(2).setResizable(false);
            crossfitTable.getColumnModel().getColumn(3).setResizable(false);
            crossfitTable.getColumnModel().getColumn(4).setResizable(false);
            crossfitTable.getColumnModel().getColumn(5).setResizable(false);
            crossfitTable.getColumnModel().getColumn(6).setResizable(false);
            crossfitTable.getColumnModel().getColumn(7).setResizable(false);
        }

        javax.swing.GroupLayout jPanel15Layout = new javax.swing.GroupLayout(jPanel15);
        jPanel15.setLayout(jPanel15Layout);
        jPanel15Layout.setHorizontalGroup(
            jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel15Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3)
                .addContainerGap())
        );
        jPanel15Layout.setVerticalGroup(
            jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 309, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jPanel15, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel14, javax.swing.GroupLayout.DEFAULT_SIZE, 805, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel15, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jLabel15.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 37, 12));
        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel15.setText("What is Crossfit?");

        javax.swing.GroupLayout crossfitPanelLayout = new javax.swing.GroupLayout(crossfitPanel);
        crossfitPanel.setLayout(crossfitPanelLayout);
        crossfitPanelLayout.setHorizontalGroup(
            crossfitPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(crossfitPanelLayout.createSequentialGroup()
                .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 840, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(crossfitPanelLayout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 699, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        crossfitPanelLayout.setVerticalGroup(
            crossfitPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(crossfitPanelLayout.createSequentialGroup()
                .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel15)
                .addGap(18, 18, 18)
                .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, 404, Short.MAX_VALUE))
        );

        Menu_item_content.add(crossfitPanel, "card4");

        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/zumba.jpg"))); // NOI18N
        jLabel16.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(242, 100, 34)));
        jLabel16.setMaximumSize(new java.awt.Dimension(867, 380));
        jLabel16.setMinimumSize(new java.awt.Dimension(867, 380));
        jLabel16.setPreferredSize(new java.awt.Dimension(867, 380));

        jPanel9.setBackground(new java.awt.Color(255, 255, 255));
        jPanel9.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 0, 0, 0, new java.awt.Color(242, 100, 34)));
        jPanel9.setPreferredSize(new java.awt.Dimension(840, 400));

        jLabel17.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel17.setText("<html>\n<p style=\"text-align: justify;\">We take the \"work\" out of workout, by mixing low-intensity and high-intensity moves for an interval-style, calorie-burning dance fitness party. Once the Latin and World rhythms take over, you'll see why Zumba Fitness classes are often called exercise in disguise</p>\n</html>");

        jPanel16.setPreferredSize(new java.awt.Dimension(805, 309));

        zumbaTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"08:00", null, null, null, null, null, null, null},
                {"10:00", null, null, null, null, null, null, null},
                {"12:00", null, null, null, null, null, null, null},
                {"14:00", null, null, null, null, null, null, null},
                {"16:00", null, null, null, null, null, null, null},
                {"18:00", null, null, null, null, null, null, null},
                {"20:00", null, null, null, null, null, null, null}
            },
            new String [] {
                "", "Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday", "Sunday"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        zumbaTable.setRowHeight(35);
        zumbaTable.getTableHeader().setReorderingAllowed(false);
        zumbaTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                zumbaTableMouseClicked(evt);
            }
        });
        jScrollPane4.setViewportView(zumbaTable);
        zumbaTable.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        if (zumbaTable.getColumnModel().getColumnCount() > 0) {
            zumbaTable.getColumnModel().getColumn(0).setResizable(false);
            zumbaTable.getColumnModel().getColumn(1).setResizable(false);
            zumbaTable.getColumnModel().getColumn(2).setResizable(false);
            zumbaTable.getColumnModel().getColumn(3).setResizable(false);
            zumbaTable.getColumnModel().getColumn(4).setResizable(false);
            zumbaTable.getColumnModel().getColumn(5).setResizable(false);
            zumbaTable.getColumnModel().getColumn(6).setResizable(false);
            zumbaTable.getColumnModel().getColumn(7).setResizable(false);
        }

        javax.swing.GroupLayout jPanel16Layout = new javax.swing.GroupLayout(jPanel16);
        jPanel16.setLayout(jPanel16Layout);
        jPanel16Layout.setHorizontalGroup(
            jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel16Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane4)
                .addContainerGap())
        );
        jPanel16Layout.setVerticalGroup(
            jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 309, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jPanel16, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel17, javax.swing.GroupLayout.DEFAULT_SIZE, 805, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel16, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jLabel18.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 37, 12));
        jLabel18.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel18.setText("What is Zumba?");

        javax.swing.GroupLayout zumbaPanelLayout = new javax.swing.GroupLayout(zumbaPanel);
        zumbaPanel.setLayout(zumbaPanelLayout);
        zumbaPanelLayout.setHorizontalGroup(
            zumbaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(zumbaPanelLayout.createSequentialGroup()
                .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 840, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addComponent(jPanel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(zumbaPanelLayout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 699, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        zumbaPanelLayout.setVerticalGroup(
            zumbaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(zumbaPanelLayout.createSequentialGroup()
                .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel18)
                .addGap(18, 18, 18)
                .addComponent(jPanel9, javax.swing.GroupLayout.DEFAULT_SIZE, 404, Short.MAX_VALUE))
        );

        Menu_item_content.add(zumbaPanel, "card5");

        jLabel19.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/yoga_1.jpg"))); // NOI18N
        jLabel19.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(242, 100, 34)));
        jLabel19.setMaximumSize(new java.awt.Dimension(867, 380));
        jLabel19.setMinimumSize(new java.awt.Dimension(867, 380));
        jLabel19.setPreferredSize(new java.awt.Dimension(867, 380));

        jPanel10.setBackground(new java.awt.Color(255, 255, 255));
        jPanel10.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 0, 0, 0, new java.awt.Color(242, 100, 34)));
        jPanel10.setPreferredSize(new java.awt.Dimension(840, 400));

        jLabel20.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel20.setText("<html>\n<p style=\"text-align: justify;\">Yoga is an ancient form of exercise that focuses on strength, flexibility and breathing to boost physical and mental wellbeing. The main components of yoga are postures (a series of movements designed to increase strength and flexibility) and breathing.</p>\n</html>");

        jPanel17.setPreferredSize(new java.awt.Dimension(805, 309));

        yogaTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"08:00", null, null, null, null, null, null, null},
                {"10:00", null, null, null, null, null, null, null},
                {"12:00", null, null, null, null, null, null, null},
                {"14:00", null, null, null, null, null, null, null},
                {"16:00", null, null, null, null, null, null, null},
                {"18:00", null, null, null, null, null, null, null},
                {"20:00", null, null, null, null, null, null, null}
            },
            new String [] {
                "", "Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday", "Sunday"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        yogaTable.setRowHeight(35);
        yogaTable.getTableHeader().setReorderingAllowed(false);
        yogaTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                yogaTableMouseClicked(evt);
            }
        });
        jScrollPane5.setViewportView(yogaTable);
        yogaTable.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        if (yogaTable.getColumnModel().getColumnCount() > 0) {
            yogaTable.getColumnModel().getColumn(0).setResizable(false);
            yogaTable.getColumnModel().getColumn(1).setResizable(false);
            yogaTable.getColumnModel().getColumn(2).setResizable(false);
            yogaTable.getColumnModel().getColumn(3).setResizable(false);
            yogaTable.getColumnModel().getColumn(4).setResizable(false);
            yogaTable.getColumnModel().getColumn(5).setResizable(false);
            yogaTable.getColumnModel().getColumn(6).setResizable(false);
            yogaTable.getColumnModel().getColumn(7).setResizable(false);
        }

        javax.swing.GroupLayout jPanel17Layout = new javax.swing.GroupLayout(jPanel17);
        jPanel17.setLayout(jPanel17Layout);
        jPanel17Layout.setHorizontalGroup(
            jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel17Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane5)
                .addContainerGap())
        );
        jPanel17Layout.setVerticalGroup(
            jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 309, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jPanel17, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel20, javax.swing.GroupLayout.DEFAULT_SIZE, 805, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel17, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jLabel21.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(255, 37, 12));
        jLabel21.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel21.setText("What is Yoga?");

        javax.swing.GroupLayout yogaPanelLayout = new javax.swing.GroupLayout(yogaPanel);
        yogaPanel.setLayout(yogaPanelLayout);
        yogaPanelLayout.setHorizontalGroup(
            yogaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(yogaPanelLayout.createSequentialGroup()
                .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 840, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addComponent(jPanel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(yogaPanelLayout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 699, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        yogaPanelLayout.setVerticalGroup(
            yogaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(yogaPanelLayout.createSequentialGroup()
                .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel21)
                .addGap(18, 18, 18)
                .addComponent(jPanel10, javax.swing.GroupLayout.DEFAULT_SIZE, 404, Short.MAX_VALUE))
        );

        Menu_item_content.add(yogaPanel, "card6");

        pilatesPanel.setForeground(new java.awt.Color(255, 37, 12));

        jLabel22.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/pilates_1.jpg"))); // NOI18N
        jLabel22.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(242, 100, 34)));
        jLabel22.setMaximumSize(new java.awt.Dimension(867, 380));
        jLabel22.setMinimumSize(new java.awt.Dimension(867, 380));
        jLabel22.setPreferredSize(new java.awt.Dimension(867, 380));

        jPanel11.setBackground(new java.awt.Color(255, 255, 255));
        jPanel11.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 0, 0, 0, new java.awt.Color(242, 100, 34)));
        jPanel11.setPreferredSize(new java.awt.Dimension(840, 400));

        jLabel23.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel23.setText("<html>\n<p style=\"text-align: justify;\">Pilates aims to strengthen the body in an even way, with particular emphasis on core strength to improve general fitness and wellbeing. Pilates has something to offer people of all ages and levels of ability and fitness, from beginners to elite athletes. The apparatus can be used to provide support for beginners and people with certain medical conditions, as well as resistance for people looking to challenge their body.</p>\n</html>");

        jPanel18.setPreferredSize(new java.awt.Dimension(805, 309));

        pilatesTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"08:00", null, null, null, null, null, null, null},
                {"10:00", null, null, null, null, null, null, null},
                {"12:00", null, null, null, null, null, null, null},
                {"14:00", null, null, null, null, null, null, null},
                {"16:00", null, null, null, null, null, null, null},
                {"18:00", null, null, null, null, null, null, null},
                {"20:00", null, null, null, null, null, null, null}
            },
            new String [] {
                "", "Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday", "Sunday"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        pilatesTable.setRowHeight(35);
        pilatesTable.getTableHeader().setReorderingAllowed(false);
        pilatesTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pilatesTableMouseClicked(evt);
            }
        });
        jScrollPane6.setViewportView(pilatesTable);
        pilatesTable.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        if (pilatesTable.getColumnModel().getColumnCount() > 0) {
            pilatesTable.getColumnModel().getColumn(0).setResizable(false);
            pilatesTable.getColumnModel().getColumn(1).setResizable(false);
            pilatesTable.getColumnModel().getColumn(2).setResizable(false);
            pilatesTable.getColumnModel().getColumn(3).setResizable(false);
            pilatesTable.getColumnModel().getColumn(4).setResizable(false);
            pilatesTable.getColumnModel().getColumn(5).setResizable(false);
            pilatesTable.getColumnModel().getColumn(6).setResizable(false);
            pilatesTable.getColumnModel().getColumn(7).setResizable(false);
        }

        javax.swing.GroupLayout jPanel18Layout = new javax.swing.GroupLayout(jPanel18);
        jPanel18.setLayout(jPanel18Layout);
        jPanel18Layout.setHorizontalGroup(
            jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel18Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane6)
                .addContainerGap())
        );
        jPanel18Layout.setVerticalGroup(
            jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane6, javax.swing.GroupLayout.DEFAULT_SIZE, 287, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jPanel18, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel23, javax.swing.GroupLayout.DEFAULT_SIZE, 805, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel23, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel18, javax.swing.GroupLayout.DEFAULT_SIZE, 287, Short.MAX_VALUE)
                .addContainerGap())
        );

        jLabel24.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(255, 37, 12));
        jLabel24.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel24.setText("What is Pilates?");

        javax.swing.GroupLayout pilatesPanelLayout = new javax.swing.GroupLayout(pilatesPanel);
        pilatesPanel.setLayout(pilatesPanelLayout);
        pilatesPanelLayout.setHorizontalGroup(
            pilatesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pilatesPanelLayout.createSequentialGroup()
                .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, 840, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addComponent(jPanel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(pilatesPanelLayout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(jLabel24, javax.swing.GroupLayout.PREFERRED_SIZE, 699, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pilatesPanelLayout.setVerticalGroup(
            pilatesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pilatesPanelLayout.createSequentialGroup()
                .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel24)
                .addGap(18, 18, 18)
                .addComponent(jPanel11, javax.swing.GroupLayout.DEFAULT_SIZE, 404, Short.MAX_VALUE))
        );

        Menu_item_content.add(pilatesPanel, "card7");

        bodybuildingPanel.setForeground(new java.awt.Color(255, 37, 12));

        jLabel25.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/bodybuilding_1.jpg"))); // NOI18N
        jLabel25.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(242, 100, 34)));
        jLabel25.setMaximumSize(new java.awt.Dimension(867, 380));
        jLabel25.setMinimumSize(new java.awt.Dimension(867, 380));
        jLabel25.setPreferredSize(new java.awt.Dimension(867, 380));

        jPanel12.setBackground(new java.awt.Color(255, 255, 255));
        jPanel12.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 0, 0, 0, new java.awt.Color(242, 100, 34)));
        jPanel12.setPreferredSize(new java.awt.Dimension(840, 400));

        jLabel26.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel26.setText("<html>\n<p style=\"text-align: justify;\">Bodybuilding is the process of developing muscle fibres through the combination of weight training, specific caloric intake, and rest. Someone who engages in this activity is referred to as a bodybuilder. As a sport, called competitive bodybuilding, bodybuilders display their physiques to a panel of judges, who assign points based on their aesthetic appearance.</p>\n</html>");

        jPanel19.setPreferredSize(new java.awt.Dimension(805, 309));

        bodybuildingTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"08:00", null, null, null, null, null, null, null},
                {"10:00", null, null, null, null, null, null, null},
                {"12:00", null, null, null, null, null, null, null},
                {"14:00", null, null, null, null, null, null, null},
                {"16:00", null, null, null, null, null, null, null},
                {"18:00", null, null, null, null, null, null, null},
                {"20:00", null, null, null, null, null, null, null}
            },
            new String [] {
                "", "Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday", "Sunday"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        bodybuildingTable.setRowHeight(35);
        bodybuildingTable.getTableHeader().setReorderingAllowed(false);
        bodybuildingTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bodybuildingTableMouseClicked(evt);
            }
        });
        jScrollPane7.setViewportView(bodybuildingTable);
        bodybuildingTable.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        if (bodybuildingTable.getColumnModel().getColumnCount() > 0) {
            bodybuildingTable.getColumnModel().getColumn(0).setResizable(false);
            bodybuildingTable.getColumnModel().getColumn(1).setResizable(false);
            bodybuildingTable.getColumnModel().getColumn(2).setResizable(false);
            bodybuildingTable.getColumnModel().getColumn(3).setResizable(false);
            bodybuildingTable.getColumnModel().getColumn(4).setResizable(false);
            bodybuildingTable.getColumnModel().getColumn(5).setResizable(false);
            bodybuildingTable.getColumnModel().getColumn(6).setResizable(false);
            bodybuildingTable.getColumnModel().getColumn(7).setResizable(false);
        }

        javax.swing.GroupLayout jPanel19Layout = new javax.swing.GroupLayout(jPanel19);
        jPanel19.setLayout(jPanel19Layout);
        jPanel19Layout.setHorizontalGroup(
            jPanel19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel19Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane7)
                .addContainerGap())
        );
        jPanel19Layout.setVerticalGroup(
            jPanel19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane7, javax.swing.GroupLayout.DEFAULT_SIZE, 287, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel12Layout = new javax.swing.GroupLayout(jPanel12);
        jPanel12.setLayout(jPanel12Layout);
        jPanel12Layout.setHorizontalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jPanel19, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel26, javax.swing.GroupLayout.DEFAULT_SIZE, 805, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel12Layout.setVerticalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel26, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel19, javax.swing.GroupLayout.DEFAULT_SIZE, 287, Short.MAX_VALUE)
                .addContainerGap())
        );

        jLabel27.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel27.setForeground(new java.awt.Color(255, 37, 12));
        jLabel27.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel27.setText("What is Bodybuilding?");

        javax.swing.GroupLayout bodybuildingPanelLayout = new javax.swing.GroupLayout(bodybuildingPanel);
        bodybuildingPanel.setLayout(bodybuildingPanelLayout);
        bodybuildingPanelLayout.setHorizontalGroup(
            bodybuildingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bodybuildingPanelLayout.createSequentialGroup()
                .addComponent(jLabel25, javax.swing.GroupLayout.PREFERRED_SIZE, 840, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addComponent(jPanel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(bodybuildingPanelLayout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(jLabel27, javax.swing.GroupLayout.PREFERRED_SIZE, 699, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        bodybuildingPanelLayout.setVerticalGroup(
            bodybuildingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bodybuildingPanelLayout.createSequentialGroup()
                .addComponent(jLabel25, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel27)
                .addGap(18, 18, 18)
                .addComponent(jPanel12, javax.swing.GroupLayout.DEFAULT_SIZE, 404, Short.MAX_VALUE))
        );

        Menu_item_content.add(bodybuildingPanel, "card8");

        jPanel1.add(Menu_item_content, java.awt.BorderLayout.CENTER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Za svaki button u meniju sa lijeve strane imamo odredjenu akciju.
     * Akcije su unutar koda nazvane na nacin:
     *      buttonName_ActionPerformed
     * Ovo znaci da ce se data funkcija (akcija) pozvati prilikom klika na odredjeni button.
     * homeButtonActionPerformed treba da prikaze pocetni ekran aplikacije na kojem se nalazi opisni tekst, te samim tim ne mora
     * da sadrzi nikakvu logiku osim "sakrivanja" ostalih panela.
     * Svaki od ekrana se nalazi na zasebnom panelu.
     */
    private void homeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_homeButtonActionPerformed
        // TODO add your handling code here:
        homePanel.setVisible(true);
        fitnessPanel.setVisible(false);
        pilatesPanel.setVisible(false);
        yogaPanel.setVisible(false);
        bodybuildingPanel.setVisible(false);
        crossfitPanel.setVisible(false);
        zumbaPanel.setVisible(false);

    }//GEN-LAST:event_homeButtonActionPerformed

    // fitnessButtonActionPerformed ima za zadatak da sakrije Home panel (i bilo koji drugi panel, ovisno s kojeg panela dolazimo na fitness),
    // te da osim toga dinamicki kreira tabelu sa rasporedom termina za fitness.
    // Tabela se sastoji od vremena termina u razmacima od 2h (od 08:00 do 20:00) predstavljeno kao redovi, te od naziva dana u sedmici predstavljeno kao kolone.
    private void fitnessButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fitnessButtonActionPerformed
        // Prvo kreiramo listu rasporeda. Klasa "Schedules" nam predstavlja objekat koji mapira tabelu Schedules koja se nalazi u bazi (Schedules je predstavljen kao entity).
        
        List<Schedules> s = new ArrayList<Schedules>();
        int fitnessProgramId = 1;
        // Jedan Schedules (ili raspored) dohvatamo iz baze koristeci Id programa za koji nam raspored treba.
        // U slucaju fitnessSchedule koristimo fitnessProgramId = 1.
        // Dati programId proslijedimo funkciji getSchedules() koja se nalazi unutar pomocne klase GetSchedules.
        // Komanda ispod poziva metodu getSchedules() iz GetSchedules klase kojoj proslijedimo programId = 1 i na osnovu kojeg ce nam iz baze dohvatiti sve 
        // redove tabele "schedules" gdje je ProgramId = 1 (dohvaca redove za fitness id).
        s = GetSchedules.getSchedules(fitnessProgramId);
        // Nakon izvrsenja komande iznad, varijabla "s" nam sadrzi potrebne podatke iz baze za fitness program.
        
        // fitnessTable.getRowCount() dohvaca ukupan broj redova u tabeli (mi ih imamo 8)
        int rowCount = fitnessTable.getRowCount();

        // koristeci for petlju ispod prolazimo kroz sve elemente iz liste rasporeda "s"
        for (int i = 0; i < s.size(); i++) {
            // s[0] je prvi element iz liste rasporeda koji predstavlja jedan objekat tipa Schedules, te za taj objekat dohvacamo dan u sedmici u kojem se dati termin nalazi,
            // kao i vrijeme kad dati termin pocinje (naprimjer: 10:00, Wednesday)
            String dayOfTheWeek = s.get(i).getDayOfTheWeek();
            String dateTime = s.get(i).getDateTime();
            
            // Komande ispod dohvacaju specificnu kolonu po njenom nazivu.
            // Vrijednosti koje citamo iz baze za atribut dayOfTheWeek odgovaraju nazivima kolona u tabeli (Wednesday == Wednesday itd).
            // Na osnovu vrijednosti atributa za npr. s[0].dayOfTheWeek (nek to bude Wednesday) mozemo dohvatiti kolonu iz tabele koja ima naziv "Wednesday".
            TableColumn tc = fitnessTable.getColumn(dayOfTheWeek);
            // tc.getModelIndex() dohvaca indeks te kolone, naprimjer za Wednesday je to cetvrta kolona, a index = 3 (posto indeksacija ide od 0).
            int colIndex = tc.getModelIndex();
            
            // for petljom ispod proci cemo kroz sve redove u tabeli (ima ih 8) i po osnovu varijable dateTime koju smo ucitali iz objekta iz baze i
            // kolone koju smo dobili iznad koristeci getColumn() mozemo smjestiti podatak o treneru u odgovarajuci red i odgovarajucu kolonu.
            for (int j = 0; j < rowCount; j++) {
                String row = fitnessTable.getValueAt(j, 0).toString(); // dohvatamo vrijeme u j-tom redu i 0-oj koloni: npr 10:00, 12:00 ili 20:00
                if (row.equals(dateTime)) {
                    // Ako vrijeme iz tabele odgovara vremenu iz baze, u taj red cemo smjestiti podatke iz baze, a u kolonu koja odgovara colIndex koji smo dohvatili
                    // pomocu naziva dana u sedmici (dayOfTheWeek).
                    fitnessTable.setValueAt(s.get(i).getTrainer().getName() + " " + s.get(i).getTrainer().getSurname(), j, colIndex);
                }
            }
        }
        
        homePanel.setVisible(false);
        fitnessPanel.setVisible(true);
        pilatesPanel.setVisible(false);
        yogaPanel.setVisible(false);
        bodybuildingPanel.setVisible(false);
        crossfitPanel.setVisible(false);
        zumbaPanel.setVisible(false);
    }//GEN-LAST:event_fitnessButtonActionPerformed

    private void crossfitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_crossfitButtonActionPerformed
        List<Schedules> s = new ArrayList<Schedules>();
        int crossfitProgramId = 2;
        s = GetSchedules.getSchedules(crossfitProgramId);
        int rowCount = crossfitTable.getRowCount();

        for (int i = 0; i < s.size(); i++) {
            String dayOfTheWeek = s.get(i).getDayOfTheWeek();
            String dateTime = s.get(i).getDateTime();
            
            TableColumn tc = crossfitTable.getColumn(dayOfTheWeek);
            int colIndex = tc.getModelIndex();
            
            for (int j = 0; j < rowCount; j++) {
                String row = crossfitTable.getValueAt(j, 0).toString();
                if (row.equals(dateTime)) {
                    crossfitTable.setValueAt(s.get(i).getTrainer().getName() + " " + s.get(i).getTrainer().getSurname(), j, colIndex);
                }
            }
        }
        
        homePanel.setVisible(false);
        fitnessPanel.setVisible(false);
        pilatesPanel.setVisible(false);
        yogaPanel.setVisible(false);
        bodybuildingPanel.setVisible(false);
        crossfitPanel.setVisible(true);
        zumbaPanel.setVisible(false);
    }//GEN-LAST:event_crossfitButtonActionPerformed

    private void zumbaButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_zumbaButtonActionPerformed
        List<Schedules> s = new ArrayList<Schedules>();
        int zumbaProgramId = 3;
        s = GetSchedules.getSchedules(zumbaProgramId);
        int rowCount = zumbaTable.getRowCount();

        for (int i = 0; i < s.size(); i++) {
            String dayOfTheWeek = s.get(i).getDayOfTheWeek();
            String dateTime = s.get(i).getDateTime();
            
            TableColumn tc = zumbaTable.getColumn(dayOfTheWeek);
            int colIndex = tc.getModelIndex();
            
            for (int j = 0; j < rowCount; j++) {
                String row = zumbaTable.getValueAt(j, 0).toString();
                if (row.equals(dateTime)) {
                    zumbaTable.setValueAt(s.get(i).getTrainer().getName() + " " + s.get(i).getTrainer().getSurname(), j, colIndex);
                }
            }
        }
        
        homePanel.setVisible(false);
        fitnessPanel.setVisible(false);
        pilatesPanel.setVisible(false);
        yogaPanel.setVisible(false);
        bodybuildingPanel.setVisible(false);
        crossfitPanel.setVisible(false);
        zumbaPanel.setVisible(true);
    }//GEN-LAST:event_zumbaButtonActionPerformed

    private void yogaButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_yogaButtonActionPerformed
        // TODO add your handling code here:
        List<Schedules> s = new ArrayList<Schedules>();
        int yogaProgramId = 4;
        s = GetSchedules.getSchedules(yogaProgramId);
        int rowCount = yogaTable.getRowCount();

        for (int i = 0; i < s.size(); i++) {
            String dayOfTheWeek = s.get(i).getDayOfTheWeek();
            String dateTime = s.get(i).getDateTime();
            
            TableColumn tc = yogaTable.getColumn(dayOfTheWeek);
            int colIndex = tc.getModelIndex();
            
            for (int j = 0; j < rowCount; j++) {
                String row = yogaTable.getValueAt(j, 0).toString();
                if (row.equals(dateTime)) {
                    yogaTable.setValueAt(s.get(i).getTrainer().getName() + " " + s.get(i).getTrainer().getSurname(), j, colIndex);
                }
            }
            // Object o = fitnessTable.getValueAt(3, colIndex);
        }
        
        homePanel.setVisible(false);
        fitnessPanel.setVisible(false);
        pilatesPanel.setVisible(false);
        yogaPanel.setVisible(true);
        bodybuildingPanel.setVisible(false);
        crossfitPanel.setVisible(false);
        zumbaPanel.setVisible(false);
    }//GEN-LAST:event_yogaButtonActionPerformed

    private void pilatesButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pilatesButtonActionPerformed
        // TODO add your handling code here:
        List<Schedules> s = new ArrayList<Schedules>();
        int pilatesProgramId = 5;
        s = GetSchedules.getSchedules(pilatesProgramId);
        int rowCount = pilatesTable.getRowCount();

        for (int i = 0; i < s.size(); i++) {
            String dayOfTheWeek = s.get(i).getDayOfTheWeek();
            String dateTime = s.get(i).getDateTime();
            
            TableColumn tc = pilatesTable.getColumn(dayOfTheWeek);
            int colIndex = tc.getModelIndex();
            
            for (int j = 0; j < rowCount; j++) {
                String row = pilatesTable.getValueAt(j, 0).toString();
                if (row.equals(dateTime)) {
                    pilatesTable.setValueAt(s.get(i).getTrainer().getName() + " " + s.get(i).getTrainer().getSurname(), j, colIndex);
                }
            }
            // Object o = fitnessTable.getValueAt(3, colIndex);
        }
        
        homePanel.setVisible(false);
        fitnessPanel.setVisible(false);
        pilatesPanel.setVisible(true);
        yogaPanel.setVisible(false);
        bodybuildingPanel.setVisible(false);
        crossfitPanel.setVisible(false);
        zumbaPanel.setVisible(false);
    }//GEN-LAST:event_pilatesButtonActionPerformed

    private void bodybuildingButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bodybuildingButtonActionPerformed
        // TODO add your handling code here:
        List<Schedules> s = new ArrayList<Schedules>();
        int bodybuildingProgramId = 6;
        s = GetSchedules.getSchedules(bodybuildingProgramId);
        int rowCount = bodybuildingTable.getRowCount();

        for (int i = 0; i < s.size(); i++) {
            String dayOfTheWeek = s.get(i).getDayOfTheWeek();
            String dateTime = s.get(i).getDateTime();
            
            TableColumn tc = bodybuildingTable.getColumn(dayOfTheWeek);
            int colIndex = tc.getModelIndex();
            
            for (int j = 0; j < rowCount; j++) {
                String row = bodybuildingTable.getValueAt(j, 0).toString();
                if (row.equals(dateTime)) {
                    bodybuildingTable.setValueAt(s.get(i).getTrainer().getName() + " " + s.get(i).getTrainer().getSurname(), j, colIndex);
                }
            }
            // Object o = fitnessTable.getValueAt(3, colIndex);
        }
        
        homePanel.setVisible(false);
        fitnessPanel.setVisible(false);
        pilatesPanel.setVisible(false);
        yogaPanel.setVisible(false);
        bodybuildingPanel.setVisible(true);
        crossfitPanel.setVisible(false);
        zumbaPanel.setVisible(false);
    }//GEN-LAST:event_bodybuildingButtonActionPerformed

    private void fitnessButtonComponentAdded(java.awt.event.ContainerEvent evt) {//GEN-FIRST:event_fitnessButtonComponentAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_fitnessButtonComponentAdded

    private void fitnessTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_fitnessTableMouseClicked
        // komanda ispod dohvaca vrijednost koja je zapisana u datom redu i datoj koloni u tabeli (ćelija koju smo selektovali)
        String rowNameSurname = (String) fitnessTable.getValueAt(fitnessTable.getSelectedRow(), fitnessTable.getSelectedColumn());
        // komanda ispod dohvata naziv kolone u kojoj je ćelija koju smo selektovali
        String dayOfTheWeek = (String) fitnessTable.getColumnName(fitnessTable.getSelectedColumn());
        
        // dohvatimo redni broj reda
        int rowIndex = fitnessTable.getSelectedRow();
        String dateTime = fitnessTable.getValueAt(rowIndex, 0).toString();
        
        // komanda ispod vraca niz od dva stringa, gdje je prvi element niza ime, drugi element niza prezime trenera
        String[] name_surname = rowNameSurname.split(" ");
        
        // komanda ispod iz baze dohvaca podatke trenera (tojest, dohvacamo Id trenera)
        int trainerId = GetTrainers.getTrainerId(name_surname[0], name_surname[1]);
        
        // komanda ispod dohvaca rezultat odgovora sa pop-up dijaloga (Yes: 0, No: 1, Cancel: 2)
        int result = JOptionPane.showConfirmDialog(this, "Do you want to book this class?");
        int programId = 1;
        if (result == 0) {
            // Ispod kreiramo novi objekat tipa Reservations i taj objekat proslijedimo metodi setReservation u klasi SetReservations koja vrsi insert u bazu u tabelu "reservations"
            Reservations res = new Reservations();
            res.setProgramId(programId);
            res.setTrainerId(trainerId);
            res.setDateTime(dateTime);
            res.setDayOfTheWeek(dayOfTheWeek);
            res.setUser("TEST");
            
            // poziv metode setReservation koja ce izvrsiti insert u bazu
            SetReservations.setReservation(res);
        }
    }//GEN-LAST:event_fitnessTableMouseClicked

    private void crossfitTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_crossfitTableMouseClicked
        // TODO add your handling code here:
        String rowNameSurname = (String) crossfitTable.getValueAt(crossfitTable.getSelectedRow(), crossfitTable.getSelectedColumn());
        String dayOfTheWeek = (String) crossfitTable.getColumnName(crossfitTable.getSelectedColumn());
        int rowIndex = crossfitTable.getSelectedRow();
        String dateTime = crossfitTable.getValueAt(rowIndex, 0).toString();

        String[] name_surname = rowNameSurname.split(" ");
        int trainerId = GetTrainers.getTrainerId(name_surname[0], name_surname[1]);
        int result = JOptionPane.showConfirmDialog(this, "Do you want to make a reservation?");
        int programId = 2;
        if (result == 0) {
            Reservations res = new Reservations();
            res.setProgramId(programId);
            res.setTrainerId(trainerId);
            res.setDateTime(dateTime);
            res.setDayOfTheWeek(dayOfTheWeek);
            res.setUser("TEST");
            
            SetReservations.setReservation(res);
        }
    }//GEN-LAST:event_crossfitTableMouseClicked

    private void zumbaTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_zumbaTableMouseClicked
        // TODO add your handling code here:
        String rowNameSurname = (String) zumbaTable.getValueAt(zumbaTable.getSelectedRow(), zumbaTable.getSelectedColumn());
        String dayOfTheWeek = (String) crossfitTable.getColumnName(zumbaTable.getSelectedColumn());
        int rowIndex = zumbaTable.getSelectedRow();
        String dateTime = zumbaTable.getValueAt(rowIndex, 0).toString();

        String[] name_surname = rowNameSurname.split(" ");
        int trainerId = GetTrainers.getTrainerId(name_surname[0], name_surname[1]);
        int result = JOptionPane.showConfirmDialog(this, "Do you want to make a reservation?");
        int programId = 3;
        if (result == 0) {
            Reservations res = new Reservations();
            res.setProgramId(programId);
            res.setTrainerId(trainerId);
            res.setDateTime(dateTime);
            res.setDayOfTheWeek(dayOfTheWeek);
            res.setUser("TEST");
            
            SetReservations.setReservation(res);
        }
    }//GEN-LAST:event_zumbaTableMouseClicked

    private void yogaTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_yogaTableMouseClicked
        // TODO add your handling code here:
        String rowNameSurname = (String) yogaTable.getValueAt(yogaTable.getSelectedRow(), yogaTable.getSelectedColumn());
        String dayOfTheWeek = (String) yogaTable.getColumnName(yogaTable.getSelectedColumn());
        int rowIndex = yogaTable.getSelectedRow();
        String dateTime = yogaTable.getValueAt(rowIndex, 0).toString();

        String[] name_surname = rowNameSurname.split(" ");
        int trainerId = GetTrainers.getTrainerId(name_surname[0], name_surname[1]);
        int result = JOptionPane.showConfirmDialog(this, "Do you want to make a reservation?");
        int programId = 4;
        if (result == 0) {
            Reservations res = new Reservations();
            res.setProgramId(programId);
            res.setTrainerId(trainerId);
            res.setDateTime(dateTime);
            res.setDayOfTheWeek(dayOfTheWeek);
            res.setUser("TEST");
            
            SetReservations.setReservation(res);
        }
    }//GEN-LAST:event_yogaTableMouseClicked

    private void pilatesTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pilatesTableMouseClicked
        // TODO add your handling code here:
        String rowNameSurname = (String) pilatesTable.getValueAt(pilatesTable.getSelectedRow(), pilatesTable.getSelectedColumn());
        String dayOfTheWeek = (String) yogaTable.getColumnName(pilatesTable.getSelectedColumn());
        int rowIndex = pilatesTable.getSelectedRow();
        String dateTime = pilatesTable.getValueAt(rowIndex, 0).toString();

        String[] name_surname = rowNameSurname.split(" ");
        int trainerId = GetTrainers.getTrainerId(name_surname[0], name_surname[1]);
        int result = JOptionPane.showConfirmDialog(this, "Do you want to make a reservation?");
        int programId = 5;
        if (result == 0) {
            Reservations res = new Reservations();
            res.setProgramId(programId);
            res.setTrainerId(trainerId);
            res.setDateTime(dateTime);
            res.setDayOfTheWeek(dayOfTheWeek);
            res.setUser("TEST");
            
            SetReservations.setReservation(res);
        }
    }//GEN-LAST:event_pilatesTableMouseClicked

    private void bodybuildingTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bodybuildingTableMouseClicked
        // TODO add your handling code here:
        String rowNameSurname = (String) bodybuildingTable.getValueAt(bodybuildingTable.getSelectedRow(), bodybuildingTable.getSelectedColumn());
        String dayOfTheWeek = (String) yogaTable.getColumnName(bodybuildingTable.getSelectedColumn());
        int rowIndex = bodybuildingTable.getSelectedRow();
        String dateTime = bodybuildingTable.getValueAt(rowIndex, 0).toString();

        String[] name_surname = rowNameSurname.split(" ");
        int trainerId = GetTrainers.getTrainerId(name_surname[0], name_surname[1]);
        int result = JOptionPane.showConfirmDialog(this, "Do you want to make a reservation?");
        int programId = 6;
        if (result == 0) {
            Reservations res = new Reservations();
            res.setProgramId(programId);
            res.setTrainerId(trainerId);
            res.setDateTime(dateTime);
            res.setDayOfTheWeek(dayOfTheWeek);
            res.setUser("TEST");
            
            SetReservations.setReservation(res);
        }
    }//GEN-LAST:event_bodybuildingTableMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Schedule.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Schedule.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Schedule.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Schedule.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Schedule().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Menu_item_content;
    private javax.swing.JPanel Menu_items;
    private javax.swing.JPanel backgroundImagePanel;
    private javax.swing.JButton bodybuildingButton;
    private javax.swing.JPanel bodybuildingPanel;
    private javax.swing.JTable bodybuildingTable;
    private javax.swing.JButton crossfitButton;
    private javax.swing.JPanel crossfitPanel;
    private javax.swing.JTable crossfitTable;
    private javax.swing.JButton fitnessButton;
    private javax.swing.JPanel fitnessPanel;
    private javax.swing.JTable fitnessTable;
    private javax.swing.JTable fitnessTable1;
    private javax.swing.JButton homeButton;
    private javax.swing.JPanel homePanel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JPanel jPanel16;
    private javax.swing.JPanel jPanel17;
    private javax.swing.JPanel jPanel18;
    private javax.swing.JPanel jPanel19;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JButton pilatesButton;
    private javax.swing.JPanel pilatesPanel;
    private javax.swing.JTable pilatesTable;
    private javax.swing.JButton yogaButton;
    private javax.swing.JPanel yogaPanel;
    private javax.swing.JTable yogaTable;
    private javax.swing.JButton zumbaButton;
    private javax.swing.JPanel zumbaPanel;
    private javax.swing.JTable zumbaTable;
    // End of variables declaration//GEN-END:variables
}
